-- CreateTable
CREATE TABLE "SpeakerSubmission" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "track" TEXT NOT NULL,
    "format" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "talkTitle" TEXT NOT NULL,
    "talkAbstract" TEXT NOT NULL,
    "talkDescription" TEXT NOT NULL,
    "learningOutcomes" TEXT NOT NULL,
    "alignment" TEXT NOT NULL,
    "speakerName" TEXT NOT NULL,
    "speakerEmail" TEXT NOT NULL,
    "countryCode" TEXT NOT NULL,
    "speakerPhone" TEXT NOT NULL,
    "speakerTitle" TEXT NOT NULL,
    "speakerBio" TEXT NOT NULL,
    "speakerPhotoUrl" TEXT NOT NULL,
    "speakerLinkedin" TEXT,
    "speakerWebsite" TEXT,
    "speakerTwitter" TEXT,
    "experience" TEXT NOT NULL,
    "speakingExp" TEXT NOT NULL,
    "pastTalks" TEXT,
    "recordingLink" TEXT,
    "specialRequirements" TEXT,
    "attendeeMaterials" TEXT,
    "additionalNotes" TEXT,
    "confirmOriginal" BOOLEAN NOT NULL,
    "confirmNonPromotional" BOOLEAN NOT NULL,
    "confirmAvailable" BOOLEAN NOT NULL,
    "confirmIteration" BOOLEAN NOT NULL,
    "confirmRecording" BOOLEAN NOT NULL,
    "confirmCoc" BOOLEAN NOT NULL,

    CONSTRAINT "SpeakerSubmission_pkey" PRIMARY KEY ("id")
);
